### PR TITLE
fix_issue_#31

### LINKED ISSUE #31: Error: Cannot find module 'react-switch-button'
I just got this Error from the build server.
The build is done with browserify like this: 

    browserify browser.js -t [ babelify --presets [ es2015 react  ] ] -t brfs -t require-globify -g uglifyify -o public/js/bundle.js -v

I got this as a dependency in my `package.json`

      "react-switch-button": "^2.2.2",

The build server downloaded version 2.3.0

Locally with the version 2.2.2 it works.

My question is, would it be better to change the version of 2.3 to 3.0 since it may break the build process?

### PR DESCRIPTION
**Pull request by Manuel-Manoury**
## What
- add babel presets dependencies
- add missing presets to the `.babelrc` file
- update the project versioning accordingly

## Why
- fix #31

### CODE REVIEW

**Comment by Manuel-Manoury** [comment]
@gfazioli can you review this please ? :)

**Comment by gfazioli** [comment]
@Manuel-Manoury done! thx

**Comment by Manuel-Manoury** [comment]
Thanks :) do you know approximately when you will release this fix ?

**Comment by gfazioli** [comment]
@Manuel-Manoury done right now! 👍

**Pull request merged**
